config/routes.rb
require 'sidekiq/web'
Kawa::Application.routes.draw do

  devise_for :users

  root :to => redirect("/pages/home")

  resources :pages
  resources :attachments
  resources :page_tags
  resources :quotes
  resources :bookmarks
  resources :links do
    resource :url_screenshot, :only  => [:create]
  end

  resources :users
  get 'l/:id'  => "short_urls#show", :as  => :short_url

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/quote.rb
class Quote 
  include Snippet

  include Authority::Abilities

  field :random, type: Float

  index({random: 1})

  belongs_to :contributor, :class_name  => "User"

  alias :quotation :data
  alias :quotation= :data=

  label :author, :source, :source_url

  after_initialize { self.random ||= rand }

  self.authorizer_name = "ResourceAuthorizer"

  def self.random(tags = nil)
    rv = rand
    quote =  where(:random.gte => rv).order_by([:random, :asc]).first
    quote ||= where(:random.lte  => rv).order_by([:random, :desc]).first
  end

end

app/controllers/quotes_controller.rb
class QuotesController < KawaController

  def show
    @quote = QuotePresenter.new(@quote)
  end

  protected

  def all
    Quote.all.order_by([:random, :desc])
  end

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= simple_form_for @quote do |f| %>
  <%= render :partial  => "/shared/form_error", :locals  => {:f  => f} %>

  <div class="row">
    <div class="col-lg-4">
      <%= f.input :author %>
    </div>
  </div>

  <div class="row">
  <div class="col-lg-4">
    <%= f.input :source %>
  </div>
  </div>

  <div class="row">
    <div class="col-lg-7">
      <%= f.input :source_url %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-7">
      <%= f.input :quotation, :as  => :text, :input_html  => {rows: 13} %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-3">
      <%= f.input :lang, :collection  => Language.supported, :label_method  => :name, :value_method  => :iso_code, input_html: {class: "col-lg-3"} %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-7">
      <%= f.input :tags, input_html: {class: "col-lg-4", value: @quote.tags.nil? ? nil : @quote.tags.join(",")} %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class  => "btn btn-primary" %> 
    <button class="btn btn-default"><%= link_to "Cancel", url_for(:back) %></button>
  </div>
<% end -%>

app/views/quotes/_quote.html.erb
<% quote = QuotePresenter.new(quote) -%>
<div class="quote fluid-row">
  <%= quote %>
  <%= render :partial  => "shared/control", :locals  => {:model  => quote.model, :edit_path  => edit_quote_path(quote.id)} %>
</div>

app/views/quotes/edit.html.erb
<%= render 'form' %>

app/views/quotes/index.html.erb
<%= render :partial  => "quote", :collection  => @quotes %>

app/views/quotes/new.html.erb
<%= render 'form' %>

app/views/quotes/show.html.erb
<%= @quote.quote %>

<%= render :partial  => 'shared/metadata', :locals  => {:presenter  => @quote} %>

<% if @quote.updatable? || @quote.deletable? %>
  <div class="form-actions row">
    <div class="col-lg-12">
      <% if @quote.updatable? %>
        <%= link_to 'Edit quote', edit_quote_path(@quote.model), :rel  => "edit-quote", :class  => "btn btn-info btn-sm", :alt  => "Edit", :title  => "Edit" %>
      <% end %>
      <% if @quote.deletable? %>
        <%= link_to 'Delete quote', @quote.model, :rel  => 'delete-quote', :method  => :delete, :data  => {:confirm  => "Are you sure?"}, :class  => "btn btn-danger btn-sm", :alt  => "Delete" %>
      <% end %>
    </div>
  </div>
<% end %>