config/routes.rb
require 'sidekiq/web'
Kawa::Application.routes.draw do

  devise_for :users

  root :to => redirect("/pages/home")

  resources :pages
  resources :attachments
  resources :page_tags
  resources :quotes
  resources :bookmarks
  resources :links do
    resource :url_screenshot, :only  => [:create]
  end

  resources :users
  get 'l/:id'  => "short_urls#show", :as  => :short_url

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_control.html.erb
<div class="control <%= html_class if defined?(html_class) %>"> 
  <% if current_or_guest_user.can_read?(model) -%>
    <span class="label label-info">
      <%= link_to 'View', model %>
    </span>
  <% end %>
  <% if current_or_guest_user.can_update?(model) -%>
    <span class="label label-info">
        <%= link_to 'Edit', edit_path %>
    </span>
  <% end %>
  <% if current_or_guest_user.can_delete?(model) %>
    <span class="label label-danger">
      <%= link_to 'Delete', model, :rel  => "delete-#{model.class.to_s.downcase}" , :method  => :delete, :data  => {:confirm  => "Are you sure?"} %>
    </span>
  <% end -%>
</div>

app/views/shared/_form_error.html.erb
<% if f.error_notification %>
  <div class="alert alert-block alert-error fade in" data-alert="alert">
    <a class="close" data-dismiss="alert" href="#">×</a>
    <p><%= f.error_notification %></p>
  </div>
<% end %>

app/views/shared/_metadata.html.erb
<div class='<%= "#{presenter.model.class.to_s.downcase}-metadata" %> row'>
  <div class="col-lg-8">
    <% if presenter.backlinks? %>
      <a href="#backlinkModal" data-toggle='modal' data-target="#backlinkModal" class='backlinks'><i class='icon-random'></i></a>
    <% end %>
    <% if presenter.private? %>
      <i class="icon-lock"></i>
    <%  end %>
    <%= presenter.created_at %>
    <%= presenter.creator %>
    <%= presenter.updated_at %>
    <%= presenter.view_count %>
  </div>
  <div class="col-lg-4 tags pull-right">
    <% if presenter.tags? %>
      <i class="icon-tags"></i>
      <% presenter.tags.each_with_index do |tag, idx| %>
        <%= link_to tag, "#{url_for(presenter.model.class)}?tag=#{tag}", :rel  => "tag" %><%= render_comma(presenter.tags, idx) %>
      <% end %>
    <% end %>
  </div>
</div>

<div id="backlinkModal" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">✕</button>
        <h3 class="modal-title">Backlinks</h3>
      </div>

      <div class="modal-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Page</th>
            </tr>
          </thead>
          <tbody>
          <% presenter.backlinks.each do |backlink| %>
            <tr>
              <td><%= link_to backlink.outbound_page.name, backlink.outbound_page %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

      <div class="modal-footer">
         <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>

    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand">川</a>
  </div>

  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="<%= 'active' if on_path?('page')  %>"><%= link_to 'Pages', pages_path %></li>
      <li class="dropdown <%= 'active' if on_path?('quote') %>">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Quotes<b class="caret"></b> </a>
        <ul class="dropdown-menu">
          <li><%= link_to "New Quote", new_quote_path %></li>
          <li class="divider"></li>
          <li><%= link_to "View all quotes", quotes_path %></li>
        </ul>
      </li>
      <li class="dropdown <%= 'active' if on_path?('bookmark') %>">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Bookmarks<b class="caret"></b> </a>
        <ul class="dropdown-menu">
          <li><%= link_to "New Bookmark", new_bookmark_path %></li>
          <li class="divider"></li>
          <li><%= link_to "View all bookmarks", bookmarks_path %></li>
        </ul>
      </li>
    </ul>
    <form action="<%= pages_path %>" class="navbar-form form-search navbar-left" role="search" method='get'>
      <div class="form-group">
        <input type="text" class="search-query form-control" placeholder="Search" name="query"/>
      </div>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in?  %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path, class: "navbar-link" %></li>
      <%end %>
    </ul>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<%= @sidebar.recently_changed_pages %>

<%= @sidebar.current_user_private_pages %>