config/routes.rb
require 'sidekiq/web'
Kawa::Application.routes.draw do

  devise_for :users

  root :to => redirect("/pages/home")

  resources :pages
  resources :attachments
  resources :page_tags
  resources :quotes
  resources :bookmarks
  resources :links do
    resource :url_screenshot, :only  => [:create]
  end

  resources :users
  get 'l/:id'  => "short_urls#show", :as  => :short_url

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/page.rb
class Page
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  include Tire::Model::Search
  include Tire::Model::Callbacks

  include Mongoid::TaggableWithContext
  include Mongoid::TaggableWithContext::AggregationStrategy::RealTime

  include Authority::Abilities

  index_name "#{Rails.env}-#{Rails.application.class.to_s.downcase}"

  taggable :tags, :separator  => ","

  before_save :process_plugins
  before_save :extract_links
  after_save :update_backlinks
  after_create :sync_backlinks
  after_destroy :sync_backlinks

  before_validation :set_default_markup

  has_and_belongs_to_many :links
  has_many :inbound_page_links, class_name: 'Backlink', inverse_of: :inbound_page
  has_many :outbound_page_links, class_name: 'Backlink', inverse_of: :outbound_page
  has_many :attachments, autosave: true, dependent: :destroy
  belongs_to :author, :class_name  => "User"
  belongs_to :last_editor, :class_name  => "User"

  scope :named, ->(name) { where(name: /^#{name}$/i) }
  scope :private, -> { where(private: true) }
  scope :authored, ->(author) { where(author_id: author.id) }
  scope :tagged, ->(tags) { all_in(tags: tags)}

  module Markup
    MARKDOWN = "markdown".freeze
  end
  
  field :name
  field :markup
  field :raw_data
  field :private, type: Mongoid::Boolean
  field :_slugs, type: Array, default: []
  index({name: 1}, {unique: true})
  slug  :name do |current_object|
    Kawa::Util::SlugBuilder.generate(current_object.slug_builder)
  end

  validates_presence_of :name, :markup, :raw_data, :author
  validates_uniqueness_of :name

  mapping do
    indexes :id, index: :not_analyzed
    indexes :name, analyzer: 'snowball', boost: 5.0
    indexes :tags, analyzer: 'keyword', boost: 2.0
    indexes :raw_data, analyzer: 'snowball'
    indexes :created_at, type: 'date' 
    indexes :updated_at, type: 'date'
    indexes :private, type: 'boolean'
  end

  self.authorizer_name = "ResourceAuthorizer"

  def self.supported_markups
    Markup.constants.map {|m| Markup.const_get(m)}
  end

  def self.search_index
    Tire.index(index_name)
  end

  def self.create_search_index
    search_index.create unless search_index.exists?
  end

  def self.elastic_search(query_str)
    tire.search(load: true) do
      query { string query_str } if query_str.present?
    end
  end

  def formatted_data(renderer = PageRenderer.new(self))
    #TODO cache result
    renderer.render
  end

  def title
    header = embedded_header
    header.empty? ? name : Loofah.fragment(header.to_html).scrub!(:strip).text
  end

  def embedded_header
    doc = Nokogiri::HTML(%{<div id="kawa-root">} + formatted_data + %{</div>})
    header = doc.css("div#kawa-root > h1:first-child")
  end

  private
  def process_plugins
    Kawa::Wiki::Plugin::Processor.new(self).process_processing_plugins(raw_data)
  end

  def extract_links
    page_links = PageLinkExtractor.new(self).extract_links
    page_links.each {|l| l.associate_to_page(self)}
    self.links = page_links
  end

  def update_backlinks
    Backlink.update_outbound_links self
  end

  def sync_backlinks
    Backlink.update_inbound_links self
  end

  def set_default_markup
    self.markup ||= Markup::MARKDOWN
  end

end

app/views/pages/_form.html.erb
<div class="row">
  <%= simple_form_for @page, :html  => { :class  => '' } do |f| %>
    <% if f.error_notification %>
      <div class="alert alert-block alert-error fade in" data-alert="alert">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <p><%= f.error_notification %></p>
      </div>
    <% end %>

    <%= f.input :name %>

    <%= f.input :raw_data, :as  => :text, :input_html  => {rows: "25"} %> 

    <%= f.input :private, :as  => :boolean %>

    <div id="attachment-container">
      <% @page.attachments.each_with_index do |a, index| %>
        <input id="page_attachment_ids[<%= index %>]" name="page[attachment_ids[<%= index %>]]" type="hidden" value="<%= a.id.to_s %>" data-attachment-index="<%= index %>">
      <% end %>
    </div>

    <div id="attachment-upload" class="dropzone">
      <% @page.attachments.each_with_index do |a, index| %>
      <div class="dz-preview dz-image-preview">
         <div class="dz-details">
            <div class="dz-filename"><span data-dz-name=""><%= a.asset_filename %></span></div> 
            <div class="dz-size" data-dz-size=""><strong><%= number_to_human_size(a.file_size)%></strong></div>  
             <img data-dz-thumbnail="" alt="<%= a.asset_filename %>" src="<%= a.asset.thumb.url %>">
           </div>  
           <a class="dz-remove remove-attachment" data-attachment-id="<%= a.id.to_s %>" href="javascript:undefined;">Remove file</a>
       </div>
      <% end %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, :class  => "btn btn-primary" %>
      <%= link_to "Cancel", url_for(:back), :class  => "btn" %>
    </div>
  <% end %>
</div>

app/views/pages/edit.html.erb
<%= render 'form' %>

app/views/pages/index.html.erb
<div class="row">
  <% if @search %>
    <form action="<%= pages_path %>" method="get">
      <input type="hidden" name="tags[]" value="<%= @search.tags.join(',') %>" id="tags" />
      <input type="submit" value="Filter" class="btn btn-sm"/>
    </form>

    <h3>Pages tagged with <%= @search.search_tags %></h3>
  <% end %>
  <ul>
    <% @pages.each do |page| %>
      <% if current_or_guest_user.can_read?(page) %>
        <li><%= link_to page.name, page %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/pages/new.html.erb
<%= render 'form' %>

app/views/pages/search_result.html.erb
<div class="row">
  <h3>Search Result</h3>

  <% unless @search.results? %>
    <div class="block-message alert-message warning">
      <p>
        No pages matched your query.
      </p>
      <% if current_user %>
        <div class="alert-actions">
          <%= @search.new_page_link_from_query :class  => "btn btn-sm", :rel  => "new-page" %>
        </div>
      <% end %>
    </div>
  <% else %>  
    <ul>
    <% @search.results.each do |page| %>
      <li><%= link_to page.name, page %></li>
    <% end %>
    </ul>

    <% if current_user && !@search.exact_match?  %>
      <div><%= @search.new_page_link_from_query :class  => "btn btn-sm", :rel  => "new-page" %></div>
    <% end  %>
  <% end %>
</div>

app/views/pages/show.html.erb
<% content_for(:page_title) { @page.title } %>
<div class="row">
  <article class="page-data col-lg-12">
    <%= @page.header %>
    <%= @page.data.html_safe %>
  </article>
</div>

<%= render :partial  => 'shared/metadata', :locals  => {:presenter => @page} %>


<% if @page.updatable? || @page.deletable?  %>
  <div class="form-actions row">
    <% if @page.updatable? %>
      <%= link_to 'Edit page', edit_page_path(@page.model), :rel  => "edit-page", :class  => "btn btn-info btn-sm", :alt  => "Edit", :title  => "Edit" %>
    <% end %>
    <% if @page.deletable? %>
      <%= link_to 'Delete page', @page.model, :rel  => 'delete-page', :method  => :delete, :data  => {confirm:  "Are you sure?"}, :class  => "btn btn-danger btn-sm", :alt  => "Delete" %>
    <% end %>
  </div>
<% end %>