config/routes.rb
require 'sidekiq/web'
Kawa::Application.routes.draw do

  devise_for :users

  root :to => redirect("/pages/home")

  resources :pages
  resources :attachments
  resources :page_tags
  resources :quotes
  resources :bookmarks
  resources :links do
    resource :url_screenshot, :only  => [:create]
  end

  resources :users
  get 'l/:id'  => "short_urls#show", :as  => :short_url

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/link.rb
class Link
  include Snippet

  include Authority::Abilities

  before_validation { self.url = self.class.clean(url) }
  before_destroy  :can_destroy? 
  before_save :update_screenshot
  before_create :create_screenshot

  field :_id, type: String, default: -> { Kawa::Util::Base62.encode(Kawa::Mongo::Sequence.next("links")).to_s }

  has_many :visits
  belongs_to :creator, :class_name  => "User"
  has_and_belongs_to_many :pages

  field :private, type: Mongoid::Boolean

  validates_uniqueness_of :data
  # validates_presence_of :creator, :data

  mount_uploader :url_screenshot, UrlScreenshotUploader

  scope :with_url, ->(url) { where(:data  => clean(url)) }

  label :title, :description

  alias :url :data
  alias :url= :data=
  alias :surl :_id

  self.authorizer_name = "LinkAuthorizer"

  def self.clean(url)
    PostRank::URI.clean(url)
  end

  #temporary until i upgrade to mongoid 3 with association callbacks
  def associate_to_page(page)
    self.creator = page.author unless creator.present?
    self.private = true if page.private && (pages.empty? || pages.all? {|p| p.private })
    self.private = false if !page.private 
    save
  end

  def record_visit(referrer, ip)
    visits << Visit.new(:referrer  => referrer, :ip  => ip)
    save
  end

  def generate_screenshot?
    url_screenshot.file.nil?
  end

  def can_destroy?
    pages.empty?
  end

  private 
  def set_id
    self._id = Kawa::Util::Base62.encode(Kawa::Mongo::Sequence.next("links")).to_s if new_record?
  end

  def update_screenshot
    if !new_record? && data_changed?
      ScreenshotGrabber.perform_async(link.id) unless data_was == url
    end
  end

  def create_screenshot
    ScreenshotGrabber.perform_async(id)
  end

end

app/controllers/links_controller.rb
class LinksController < KawaController
  prohibit :destroy

  respond_to :json, :html

  def show
    authorize_action_for(@link)
    respond_with(@link) do |format|
      format.json { render :json  => @link, :serializer  => LinkSerializer }
      format.html { @link = LinkPresenter.new(@link) }
    end
  end

  protected
  def all
    Link.order_by(created_at: -1).page params[:page]
  end
end

app/views/links/_form.html.erb
<div class="row">
  <%= simple_form_for @link do |f| %>
    <%= render :partial  => "/shared/form_error", :locals  => {:f  => f} %>

    <div class="row">
      <div class="col-lg-7">
        <%= f.input :url %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-7">
        <%= f.input :title %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-7">
        <%= f.input :description, :as  => :text, :input_html  => {:class  => "col-lg-8", :rows  => 10} %> 
      </div>
    </div>
    <div class="row">
      <div class="col-lg-2">
        <%= f.input :private, :as  => :boolean %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-7">
        <%= f.input :tags, input_html: {value: @link.tags.nil? ? nil : @link.tags.join(",")} %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.button :submit, :class  => "btn btn-primary" %>
      <%= link_to "Cancel", url_for(:back), :class  => "btn" %>
    </div>
  <% end %>
</div>

app/views/links/_link.html.erb
<% if current_or_guest_user.can_read?(link) %>
  <% link = LinkPresenter.new(link) %>
  <div class="link row">
    <div>
      <div class="thumbnails col-lg-2" >
        <%= link.url_screenshot_thumbnail %>
      </div>
    </div>
    <div class="col-lg-10">
      <%= link.link %>
    </div>
    <%= render :partial  => "shared/control", 
      :locals  => {:model  => link.model, 
                   :html_class  => "col-lg-12",
                   :edit_path  => edit_polymorphic_path(link.model)} %>
  </div>
<% end %>

app/views/links/edit.html.erb
<%= render 'links/form' %>

app/views/links/index.html.erb
<%= render :partial  => "links/link", :collection  => @links %>

<%= paginate @links %>

app/views/links/new.html.erb
<%= render 'links/form' %>

app/views/links/show.html.erb
<div class="row">
    <div class="col-lg-2 link-screenshot">
      <%= @link.url_screenshot_thumbnail %>

      <% if current_user %>
        <%= form_tag link_url_screenshot_path(@link.model), :remote  => true do %>
          <%= submit_tag "Regenerate", :class  => "btn btn-xs btn-default" %>
        <% end %>
      <% end %>
    </div>

    <div class="col-lg-10">
      <%= @link.link %>
      <% if @link.description %>
        <p><%= @link.description %></p>
      <% end -%>

      <div class="pages">
        <% if @link.pages.present? %>
          <h6>Pages</h6>
          <ul>
            <% @link.pages.each do |page| %>
              <% if current_or_guest_user.can_read?(page) %>
                <li><%= link_to page.name, page_path(page) %></li>
              <% end %>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>

</div>

<%= render :partial  => 'shared/metadata', :locals  => {:presenter  => @link} %>